spring:
  h2:
    console:
      path: /h2-console   # h2 web consloe 路径
      enabled: true       # 开启 h2 web consloe，默认为 false
      settings:
        web-allow-others: true    #允许远程访问 h2 web consloe

  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: bosPoolName
      connection-timeout: 30000
      max-lifetime: 1800000
      idle-timeout: 600000

management:
  endpoints:
    web:
      exposure:
        include: '*'

foo:
  datasource:
    username: sa
    url: jdbc:h2:mem:test
    driver-class-name:  org.h2.Driver
    initialization-mode: always
bar:
  datasource:
    username: sa
    url: jdbc:h2:mem:test
    driver-class-name:  org.h2.Driver
    initialization-mode: always
